# Generated by Django 5.2.1 on 2025-05-27 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_core', '0002_ninitial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='semester',
        ),
        migrations.CreateModel(
            name='ResearchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_core.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_core.task')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
