# Generated by Django 5.2.1 on 2025-05-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_core', '0003_remove_task_semester_researchprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='difficulty_level',
            field=models.CharField(choices=[('BEGINNER', 'Начинающий'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый')], default='BEGINNER', max_length=12),
        ),
    ]
