# Generated by Django 5.2.1 on 2025-05-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_core', '0004_ebook_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
