# Generated by Django 5.2.1 on 2025-05-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_core', '0005_ebook_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='link',
            field=models.CharField(default='https://library.bmstu.ru/Catalog/Details/IPRBooks/61490#fulltext', max_length=255),
            preserve_default=False,
        ),
    ]
