# Generated by Django 5.2.1 on 2025-05-28 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_core', '0007_notification_recommendation_recommendationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='author',
            field=models.CharField(default='elk', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='link',
            field=models.CharField(default='cur', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='title',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
